"""create recommendation reminder consultation message tables

Revision ID: 972c6d34c494
Revises: f81721cea54f
Create Date: 2026-10-07 01:54:36.686220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972c6d34c494'
down_revision = 'f81721cea54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('maternal_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('Pending', 'Accepted', 'Declined', 'Closed')", name='ck_consultation_status'),
    sa.CheckConstraint('(child_id IS NOT NULL AND maternal_id IS NULL) OR (child_id IS NULL AND maternal_id IS NOT NULL)', name='ck_consultation_subject'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['maternal_id'], ['maternal_profiles.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultations_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultations_requester_id'), ['requester_id'], unique=False)

    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('maternal_id', sa.Integer(), nullable=True),
    sa.Column('plan_details', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=10), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('doctor_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['maternal_id'], ['maternal_profiles.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_maternal_id'), ['maternal_id'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('maternal_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('Pending', 'Completed', 'Snoozed', 'Missed')", name='ck_reminder_status'),
    sa.CheckConstraint("type IN ('Vaccination', 'Medicine', 'Checkup', 'Nutrition', 'Other')", name='ck_reminder_type'),
    sa.CheckConstraint('(child_id IS NOT NULL AND maternal_id IS NULL) OR (child_id IS NULL AND maternal_id IS NOT NULL)', name='ck_reminder_owner'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['maternal_id'], ['maternal_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_maternal_id'), ['maternal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_scheduled_at'), ['scheduled_at'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_consultation_id'), ['consultation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_consultation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_maternal_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_child_id'))

    op.drop_table('reminders')
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_maternal_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_child_id'))

    op.drop_table('recommendation')
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultations_requester_id'))
        batch_op.drop_index(batch_op.f('ix_consultations_doctor_id'))

    op.drop_table('consultations')
    # ### end Alembic commands ###
