"""create doctor and maternal profile tables

Revision ID: f81721cea54f
Revises: d2ba5f4e6edb
Create Date: 2026-10-07 01:31:52.380061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81721cea54f'
down_revision = 'd2ba5f4e6edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.String(length=120), nullable=False),
    sa.Column('license_no', sa.String(length=50), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=10), nullable=False),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("verification_status IN ('Pending', 'Verified', 'Rejected')", name='ck_doctor_verification_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_no'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('maternal_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('conditions', sa.String(length=255), nullable=True),
    sa.Column('dietary_habits', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maternal_profiles')
    op.drop_table('doctor_profiles')
    # ### end Alembic commands ###
